version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          command: add-apt-repository ppa:team-gcc-arm-embedded/ppa
      - run:
          command: apt-get update
      - run:
          command: apt-get install --force-yes sudo python-setuptools cmake build-essential ninja-build python-dev libffi-dev libssl-dev srecord gcc-arm-embedded
      - run:
          command: easy_install pip
      - checkout
      - run:
          command: chmod +x Scripts/Build.sh
      - run:
          command: ./Scripts/Build.sh
